import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Hi, I&apos;m Jose 🧑🏽</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>Welcome to my portfolio!</h1>

			<style jsx>{`
				h1 {
					text-align: center;
					color: #f2a;
				}
			`}</style>
		</div>
	);
}
