import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import redPattern from '@assets/images/red-pattern.svg';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hi, I&apos;m Jose 🧑🏽</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-4xl font-bold text-blue-500 text-center">Welcome to my portfolio!</h1>
      <Image src={redPattern} alt="red pattern" width={200} height={200} className="mx-auto" />
      {/* <style jsx>{`
        h1 {
          text-align: center;
          color: #f2a;
          margin-top: 40px;
        }
      `}</style> */}
    </div>
  );
}
