import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Footer, Navbar } from '@components/index';
import avatar from '@assets/images/avatar.png';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hi, I&apos;m Jose 🧑🏽</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-4xl font-bold text-primary text-center">Welcome to my portfolio!</h1>
      <div className="bg-red-500 w-16 h-16 rounded-full relative">
        <Image src={avatar} width={200} height={200} />
      </div>
      {/* <style jsx>{`
        h1 {
          text-align: center;
          color: #f2a;
          margin-top: 40px;
        }
      `}</style> */}
    </div>
  );
}
